name: Build Sysroot

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -q && apt-get install -yq --no-install-recommends build-essential g++ gdb-multiarch qemu-user-static
    - name: Initialize directory structure
      run: ./utils/init-common.sh
    - name: Download Raspbian image
      run: ./utils/download-raspbian.sh
    - name: Build sysroot
      run: ./utils/prepare-sysroot-full.sh
    - name: Create minimal sysroot variant
      run: ./utils/prepare-sysroot-minimal.sh
