name: Build Sysroot

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -q && sudo apt-get install -yq --no-install-recommends build-essential gdb-multiarch qemu-user-static
    - name: Initialize directory structure
      run: ./utils/init-common.sh
    - name: Download Raspbian image
      run: ./utils/download-raspbian.sh
    - name: Build sysroot
      run: ./utils/prepare-sysroot-full.sh
    - name: Create minimal sysroot variant
      run: ./utils/prepare-sysroot-minimal.sh
    - name: Zip full sysroot
      run: zip ./sysroot-minimal.zip /opt/qtrpi/raspbian/sysroot-minimal/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: sysroot-minimal
        path: ./sysroot-minimal.zip
